const mongoose = require('mongoose');

const bookmarkSchema = new mongoose.Schema({
    userID:{
        type:String,
        required:true,
        min:6,
        max:255
    },
    ticketID:{
        type:String,
        required:true,
        min:6,
        max:255,
    },
    name:{
        type:String,
        required:true,
        min:6,
        max:255
    },
    deptName:{
        type:String,
        required:true,
        min:6,
        max:255
    },
    price:{
        type:Number
    },
    start:{
        type:String,
        required:true,
        min:2,
        max:255
    },
    dest:{
        type:String,
        required:true,
        min:2,
        max:255
    },
    duration:{
        type:String,
        required:true,
        min:2,
        max:255
    },
    departureTime:{
        type:String,
        required:true,
        min:2,
        max:255
    },
    arrivalTime:{
        type:String,
        required:true,
        min:2,
        max:255
    },
    company:{
        type:String,
        required:true,
        min:2,
        max:255
    },
    image:{
        type:String,
        min:1,
        max:255
    },
    quota:{
        type:Number
    },
});

module.exports = mongoose.model('Bookmark',bookmarkSchema);
