const mongoose = require('mongoose');
const Ticket = require('./Ticket');

const orderSchema = new mongoose.Schema({
    //orderID, auto gen
    userID:{
        type:String,
        required:true,
        min:1,
        max:255
    },
    ticketID:{
        type:String,
        required:true,
        min:1,
        max:255
    },
    userName:{
        type:String,
        required:true,
        min:1,
        max:255
    },
    name:{
        type:String,
        required:true,
        min:1,
        max:255
    },
    customerName:{
        type:String,
        required:true,
        min:1,
        max:255
    },
    gender:{
        type:String,
        required:true,
        min:1,
        max:255
    },
    departureDate:{
        type:String,
        required:true,
        min:1,
        max:255
    },
    departureTime:{
        type:String,
        required:true,
        min:1,
        max:255
    },
    arrivalTime:{
        type:String,
        required:true,
        min:1,
        max:255
    },

    passport:{
        type:String,
        required:true,
        min:1,
        max:255
    },
    price:{
        type:Number
    },
    total:{
        type:String,
        required:true,
        min:1,
        max:255
    },
    start:{
        type:String,
        required:true,
        min:2,
        max:255
    },
    dest:{
        type:String,
        required:true,
        min:2,
        max:255
    },
    duration:{
        type:String,
        required:true,
        min:2,
        max:255
    },
    company:{
        type:String,
        required:true,
        min:2,
        max:255
    },
    image:{
        type:String,
        min:1,
        max:255
    },
    quota:{
        type:Number
    },
    airClass:{
        type:String,
        min:1,
        max:255
    },
    meal:{
        type:String,
        min:1,
        max:255
    }
    
});

module.exports = mongoose.model('Order',orderSchema);
